services:

  spring-cloud-config-server:
    build: ../spring-cloud-config-server
    container_name: config-server
    ports:
      - "8888:8888"

  db:
    image: postgres:15
    container_name: tasktracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasktracker
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: tasktracker-app

    depends_on:
      db:
        condition: service_healthy
      spring-cloud-config-server:
        condition: service_started

    environment:
      # ✅ DB config
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasktracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

      # ✅ Config Server (THIS is where it goes)
      CONFIG_SERVER_URL: http://spring-cloud-config-server:8888

    ports:
      - "8099:8099"