spring:
  application:
    name: task-tracking

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasktracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      connection-timeout: 30000

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

    #     http://localhost:8888/{application}/{profile}[/{label}]
    #    application → the name of your Spring Boot app (task-tracking)
    #    profile → Spring profile (dev, prod, etc.)
    #    label → optional Git branch (default: main)
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,env,configprops,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  metrics:
    enable:
      jvm: true  # Ensure this is not set to false
    tags:
      application: task-tracking

logging:
  level:
    com:
      omnipotent:
        task_tracking: DEBUG