server:
  port: 8099

spring:
  application:
    name: task-tracking
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
#    config:
#      fail-fast:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasktracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, env, prometheus, refresh
  metrics:
    tags:
      application: task-tracking
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    refresh:
      enabled: true
    prometheus:
      access: unrestricted
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    root: INFO