apiVersion: v1
kind: ConfigMap
metadata:
  name: task-tracking-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8099"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/taskdb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_SHOW_SQL: "false"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"