apiVersion: v1
kind: Secret
metadata:
  name: task-tracking-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: bXlTdHJvbmdQYXNzd29yZA==


# echo -n "postgres" | base64
#  echo -n "myStrongPassword" | base64